name: Daily

on:
  schedule:
    - cron: '0 17 * * *' 
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
          ref: main
          
      - name: daily
        run: echo "$(date)" >> log.txt

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Crys"
          git config user.email "alungsj112@gmail.com"
          git add log.txt
          git commit -m "Automated daily commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
