name: Daily

on:
  schedule:
    - cron: '0 16 * * *' 
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: daily
        run: echo "$(date)" >> log.txt

      - name: Commit and push
        run: |
          git config --global user.name "Crys"
          git add log.txt
          git commit -m "Daily"
          git push origin main
